// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ANDROID CONFIG (YOUR FIREBASE)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdKM0zFVbetMmHTf9qSv4A6m_Lud1ldCA',
    appId: '1:1390476448:android:cf45a50fac591ec62a5dc5',
    messagingSenderId: '1390476448',
    projectId: 'vasflutter',
    storageBucket: 'vasflutter.firebasestorage.app',
  );

  // IOS CONFIG (YOUR FIREBASE)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6YvV0dlZuqPwsIpOtcTwupyxCuAZ7_QM',
    appId: '1:1390476448:ios:584ca0b1b48467342a5dc5',
    messagingSenderId: '1390476448',
    projectId: 'vasflutter',
    storageBucket: 'vasflutter.firebasestorage.app',
    iosBundleId: 'com.example.vasFlutter',
  );
}
